# Generated by Django 4.1.1 on 2022-09-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['birthday'], name='table_user_birthda_dff966_idx'),
        ),
    ]
