# Generated by Django 4.1.1 on 2022-09-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_user_table_user_birthda_dff966_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='table_user_birthda_dff966_idx',
        ),
    ]
