# Generated by Django 4.1.1 on 2022-09-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_remove_user_table_user_birthda_dff966_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-birthday'], name='table_user_birthda_da6116_idx'),
        ),
    ]
