# Generated by Django 4.1.1 on 2022-10-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0006_user_table_user_birthda_dff966_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('currency', models.CharField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
