# Generated by Django 4.1.1 on 2022-10-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0007_country_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['birthday'], name='table_user_birthda_dff966_idx'),
        ),
    ]
